{"id":159696,"global_id":"Z2lkOi8vaGFja2Vyb25lL1JlcG9ydC8xNTk2OTY=","url":"https://hackerone.com/reports/159696","title":"Two vulnerabilities in the ssl module","state":"Closed","substate":"resolved","readable_substate":"Resolved","created_at":"2016-08-16T09:41:04.755Z","submitted_at":"2016-08-16T09:41:04.755Z","is_member_of_team?":false,"reporter":{"disabled":false,"username":"tehybel","url":"/tehybel","profile_picture_urls":{"small":"/assets/avatars/default-71a302d706457f3d3a31eb30fa3e73e6cf0b1d677b8fa218eaeaffd67ae97918.png"},"is_me?":false,"cleared":false,"hackerone_triager":false,"hacker_mediation":false},"team":{"id":27,"url":"https://hackerone.com/ibb-python","handle":"ibb-python","profile_picture_urls":{"small":"https://profile-photos.hackerone-user-content.com/variants/000/000/027/c46b79d4c73a7b34d61a717ed19ae719a0b67b2e_original.png/3afcb5c896247e7ee8ada31b1c1eb8657e22241f911093acfe4ec7e97a3a959a","medium":"https://profile-photos.hackerone-user-content.com/variants/000/000/027/c46b79d4c73a7b34d61a717ed19ae719a0b67b2e_original.png/eb31823a4cc9f6b6bb4db930ffdf512533928a68a4255fb50a83180281a60da5"},"permissions":[],"submission_state":"open","default_currency":"usd","awards_miles":false,"offers_bounties":true,"state":"public_mode","only_cleared_hackers":false,"profile":{"name":"Python (IBB)","twitter_handle":"","website":"http://www.python.org/news/security","about":""}},"has_bounty?":true,"in_validation?":false,"rejected_anc_report_that_can_be_sent_back_to_anc_triagers?":false,"can_view_team":true,"can_view_report":true,"is_external_bug":false,"is_published":false,"is_participant":false,"stage":4,"public":true,"visibility":"full","cve_ids":[],"singular_disclosure_disabled":false,"disclosed_at":"2019-11-12T09:01:44.536Z","bug_reporter_agreed_on_going_public_at":null,"team_member_agreed_on_going_public_at":"2019-10-13T09:01:44.141Z","comments_closed?":false,"facebook_team?":false,"team_private?":false,"vulnerability_information":"I found two vulnerabilities in python's ssl module. \n\nThe first is a Py_XDECREF call on an object which isn't owned, leading to use-after-free and/or double free scenarios.\nThe second vulnerability is an uninitialized variable use. \n  \nI described both issues in detail in a mail to the PSRT. The mail and fix for both issues is here:\n\nhttps://bugs.python.org/issue27773","vulnerability_information_html":"\u003cp\u003eI found two vulnerabilities in python\u0026#39;s ssl module. \u003c/p\u003e\n\n\u003cp\u003eThe first is a Py_XDECREF call on an object which isn\u0026#39;t owned, leading to use-after-free and/or double free scenarios.\u003cbr\u003e\nThe second vulnerability is an uninitialized variable use. \u003c/p\u003e\n\n\u003cp\u003eI described both issues in detail in a mail to the PSRT. The mail and fix for both issues is here:\u003c/p\u003e\n\n\u003cp\u003e\u003ca title=\"https://bugs.python.org/issue27773\" href=\"/redirect?url=https%3A%2F%2Fbugs.python.org%2Fissue27773\" target=\"_blank\" rel=\"nofollow noopener noreferrer\"\u003e\u003cspan\u003ehttps://bugs.python.org/issue27773\u003c/span\u003e\u003ci class=\"icon-external-link\"\u003e\u003c/i\u003e\u003c/a\u003e\u003c/p\u003e\n","bounty_amount":"500.0","formatted_bounty":"$500","original_report_id":null,"original_report_url":null,"attachments":[],"allow_singular_disclosure_at":"2019-11-12T09:01:44.205Z","allow_singular_disclosure_after":-35667292.403452,"singular_disclosure_allowed":true,"vote_count":1,"voters":["dyabla"],"structured_scope":null,"abilities":{"assignable_team_members":[],"assignable_team_member_groups":[]},"can_edit_custom_fields_attributes":false,"activities":[{"id":1168437,"is_internal":false,"editable":false,"type":"Activities::BugNeedsMoreInfo","message":"Hey @tehybel - the maintainers flagged this as a crash rather than a security issue. We haven't done a deeper analysis, but could you provide us with your interpretation of the bug's exploitability and impact?","markdown_message":"\u003cp\u003eHey \u003ca href=\"/tehybel\"\u003e@tehybel\u003c/a\u003e - the maintainers flagged this as a crash rather than a security issue. We haven\u0026#39;t done a deeper analysis, but could you provide us with your interpretation of the bug\u0026#39;s exploitability and impact?\u003c/p\u003e\n","automated_response":false,"created_at":"2016-09-01T20:52:22.793Z","updated_at":"2016-09-01T20:52:22.793Z","actor":{"username":"arice","cleared":false,"url":"/arice","profile_picture_urls":{"medium":"https://profile-photos.hackerone-user-content.com/variants/000/000/020/83152cb2d070f3f6a63c1b61bae47257722b5ad2_original.jpeg/eb31823a4cc9f6b6bb4db930ffdf512533928a68a4255fb50a83180281a60da5"},"hackerone_triager":false,"hackerone_employee":true},"genius_execution_id":null,"team_handle":"ibb-python","actor_is_team_member":false,"actor_is_concealed_member":false},{"id":1168850,"is_internal":false,"editable":false,"type":"Activities::BugNew","message":"Hi @arice, thanks for looking into this and for the bounties!\n\nThe python developers tend to tag this type of issue as a crash. I do not know why they prefer this.\n\nI clicked three recent bugs which others reported (and got rewarded for) and all three were also tagged as crashes: \nhttps://hackerone.com/reports/129771\nhttps://hackerone.com/reports/104033\nhttps://hackerone.com/reports/104032\n\nSo I don't think the tag means much, it seems more like a default to me.\n\nAbout the concrete issue I reported: It's a use-after-free and my PoC shows that a variable can be fully controlled. So my interpretation is that it's very likely exploitable. \n\nThe impact is less clear; if an attacker can make the call to PyWeakref_NewRef in newPySSLSocket fail for any reason, the use-after-free occurs. I do not know which applications expose newPySSLSocket to an attacker with sufficient control.\n","markdown_message":"\u003cp\u003eHi \u003ca href=\"/arice\"\u003e@arice\u003c/a\u003e, thanks for looking into this and for the bounties!\u003c/p\u003e\n\n\u003cp\u003eThe python developers tend to tag this type of issue as a crash. I do not know why they prefer this.\u003c/p\u003e\n\n\u003cp\u003eI clicked three recent bugs which others reported (and got rewarded for) and all three were also tagged as crashes: \u003cbr\u003e\n\u003ca title=\"https://hackerone.com/reports/129771\" href=\"https://hackerone.com/reports/129771\"\u003ehttps://hackerone.com/reports/129771\u003c/a\u003e\u003cbr\u003e\n\u003ca title=\"https://hackerone.com/reports/104033\" href=\"https://hackerone.com/reports/104033\"\u003ehttps://hackerone.com/reports/104033\u003c/a\u003e\u003cbr\u003e\n\u003ca title=\"https://hackerone.com/reports/104032\" href=\"https://hackerone.com/reports/104032\"\u003ehttps://hackerone.com/reports/104032\u003c/a\u003e\u003c/p\u003e\n\n\u003cp\u003eSo I don\u0026#39;t think the tag means much, it seems more like a default to me.\u003c/p\u003e\n\n\u003cp\u003eAbout the concrete issue I reported: It\u0026#39;s a use-after-free and my PoC shows that a variable can be fully controlled. So my interpretation is that it\u0026#39;s very likely exploitable. \u003c/p\u003e\n\n\u003cp\u003eThe impact is less clear; if an attacker can make the call to PyWeakref_NewRef in newPySSLSocket fail for any reason, the use-after-free occurs. I do not know which applications expose newPySSLSocket to an attacker with sufficient control.\u003c/p\u003e\n","automated_response":false,"created_at":"2016-09-02T00:56:17.223Z","updated_at":"2016-09-02T00:56:17.223Z","actor":{"username":"tehybel","cleared":false,"url":"/tehybel","profile_picture_urls":{"medium":"/assets/avatars/default-71a302d706457f3d3a31eb30fa3e73e6cf0b1d677b8fa218eaeaffd67ae97918.png"},"hackerone_triager":false,"hackerone_employee":false},"genius_execution_id":null,"team_handle":"ibb-python","actor_is_team_member":false,"actor_is_concealed_member":false},{"id":1168856,"is_internal":false,"editable":false,"type":"Activities::Comment","message":"I forgot to mention that the title here says \"two vulnerabilities\" -- but the second one is unlikely to have any impact as it can't be reliably triggered by an attacker. I described that in more detail in the link I sent you. Therefore feel free to ignore the second issue.","markdown_message":"\u003cp\u003eI forgot to mention that the title here says \u0026quot;two vulnerabilities\u0026quot; -- but the second one is unlikely to have any impact as it can\u0026#39;t be reliably triggered by an attacker. I described that in more detail in the link I sent you. Therefore feel free to ignore the second issue.\u003c/p\u003e\n","automated_response":false,"created_at":"2016-09-02T01:02:10.694Z","updated_at":"2016-09-02T01:02:10.694Z","actor":{"username":"tehybel","cleared":false,"url":"/tehybel","profile_picture_urls":{"medium":"/assets/avatars/default-71a302d706457f3d3a31eb30fa3e73e6cf0b1d677b8fa218eaeaffd67ae97918.png"},"hackerone_triager":false,"hackerone_employee":false},"genius_execution_id":null,"team_handle":"ibb-python","actor_is_team_member":false,"actor_is_concealed_member":false},{"id":1205680,"is_internal":false,"editable":false,"type":"Activities::BugResolved","message":"Thanks!","markdown_message":"\u003cp\u003eThanks!\u003c/p\u003e\n","automated_response":false,"created_at":"2016-09-20T04:00:19.929Z","updated_at":"2016-09-20T04:00:19.929Z","actor":{"username":"arice","cleared":false,"url":"/arice","profile_picture_urls":{"medium":"https://profile-photos.hackerone-user-content.com/variants/000/000/020/83152cb2d070f3f6a63c1b61bae47257722b5ad2_original.jpeg/eb31823a4cc9f6b6bb4db930ffdf512533928a68a4255fb50a83180281a60da5"},"hackerone_triager":false,"hackerone_employee":true},"reporter":{"username":"tehybel","url":"/tehybel"},"genius_execution_id":null,"team_handle":"ibb-python","actor_is_team_member":false,"actor_is_concealed_member":false},{"id":1205681,"is_internal":false,"editable":false,"type":"Activities::BountyAwarded","message":"","markdown_message":"","automated_response":false,"created_at":"2016-09-20T04:00:24.792Z","updated_at":"2016-09-20T04:00:24.792Z","actor":{"url":"/ibb-python","ibb":true,"profile_picture_urls":{"medium":"https://profile-photos.hackerone-user-content.com/variants/000/000/027/c46b79d4c73a7b34d61a717ed19ae719a0b67b2e_original.png/eb31823a4cc9f6b6bb4db930ffdf512533928a68a4255fb50a83180281a60da5"},"profile":{"name":"Python (IBB)"}},"bounty_amount":"500.0","bounty_currency":"usd","genius_execution_id":null,"team_handle":"ibb-python","collaborator":{"username":"tehybel","url":"/tehybel"},"actor_is_team_member":false,"actor_is_concealed_member":false},{"id":6025394,"is_internal":false,"editable":false,"type":"Activities::AgreedOnGoingPublic","message":"","markdown_message":"","automated_response":false,"created_at":"2019-10-13T09:01:44.153Z","updated_at":"2019-10-13T09:01:44.153Z","first_to_agree":true,"actor":{"username":"reed","cleared":false,"url":"/reed","profile_picture_urls":{"medium":"https://profile-photos.hackerone-user-content.com/variants/000/003/132/66d7eadcea16b878bb67bfd697b9542250a801a7_original.jpg/eb31823a4cc9f6b6bb4db930ffdf512533928a68a4255fb50a83180281a60da5"},"hackerone_triager":false,"hackerone_employee":true},"genius_execution_id":null,"team_handle":"ibb-python","actor_is_team_member":true,"actor_is_concealed_member":false},{"id":6285219,"is_internal":false,"editable":false,"type":"Activities::ReportBecamePublic","message":"","markdown_message":"","automated_response":false,"created_at":"2019-11-12T09:01:44.548Z","updated_at":"2019-11-12T09:01:44.548Z","actor":{"url":"/ibb-python","ibb":true,"profile_picture_urls":{"medium":"https://profile-photos.hackerone-user-content.com/variants/000/000/027/c46b79d4c73a7b34d61a717ed19ae719a0b67b2e_original.png/eb31823a4cc9f6b6bb4db930ffdf512533928a68a4255fb50a83180281a60da5"},"profile":{"name":"Python (IBB)"}},"genius_execution_id":null,"team_handle":"ibb-python","actor_is_team_member":false,"actor_is_concealed_member":false}],"activity_page_count":1,"activity_page_number":1,"summaries":[{"category":"team","can_view?":true,"can_create?":false},{"category":"researcher","can_view?":true,"can_create?":false}]}